INSERT INTO clientes(nombre,apellido,email,create_at) VALUES('Andres','Guzmnan', 'aguzman@gmail.com','2018-01-01');
INSERT INTO clientes(nombre,apellido,email,create_at) VALUES('Mr Jhhn','Doe', 'jhon@gmail.com','2018-01-02');
INSERT INTO clientes(nombre,apellido,email,create_at) VALUES('Juan','Reyes', 'jreyes@gmail.com','2018-01-03');
INSERT INTO clientes(nombre,apellido,email,create_at) VALUES('Natasha','claush', 'nclaush@gmail.com','2018-01-04');
INSERT INTO clientes(nombre,apellido,email,create_at) VALUES('Miram','perez', 'mperez@gmail.com','2018-01-05');
INSERT INTO clientes(nombre,apellido,email,create_at) VALUES('Clara','Restrepo', 'crestrep@gmail.com','2018-01-06');
INSERT INTO clientes(nombre,apellido,email,create_at) VALUES('Margarita','Tabares', 'mtabares@gmail.com','2018-01-07');
INSERT INTO clientes(nombre,apellido,email,create_at) VALUES('Luis','Escobar', 'ldescobar@gmail.com','2018-01-08');
INSERT INTO clientes(nombre,apellido,email,create_at) VALUES('Gloria','Ortiz', 'gortiz@gmail.com','2018-01-09');
INSERT INTO clientes(nombre,apellido,email,create_at) VALUES('Carmen','Guzmnan', 'cguzman@gmail.com','2018-01-10');
INSERT INTO clientes(nombre,apellido,email,create_at) VALUES('Cristhian','Tamayo', 'ctamayo@gmail.com','2018-01-11');